### ISSUE TITLE
Epic: Level Maker

### ISSUE THREAD

**Issue by kaiway-tang** [jabbapen/Confectionary-Carnage#3]

**Comment by ininfallible** [comment]
# Requirements
- [ ] Add/remove tiles
- [ ] Add/remove enemies
- [ ] Menu to switch between tiles/enemies
- [ ] Save
- [ ] Upload to server
