### ISSUE TITLE
Epic: Base Infrastructure

### ISSUE THREAD

**Issue by kaiway-tang** [jabbapen/Confectionary-Carnage#5]

**Comment by ininfallible** [comment]
# Requirements
- [ ] Python: FastAPI backend for storing arbitrary files associated with a level ID 
- [ ] Unity: Level serialization
- [ ] Unity: API call to store a level
- [ ] Unity: API call to load a level
